version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres-seguros
    environment:
      POSTGRES_DB: seguros_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  core-service:
    build: ./ms-coreservice
    container_name: ms-coreservice
    ports:
      - "8082:8082"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/seguros_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - JPA_DDL_AUTO=update
      - STORAGE_LOCATION=/app/uploads
      - EVALUACION_SERVICE_URL=http://ms-evaluacion:8083
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - db

  evaluacion-service:
    build: ./ms-evaluacion
    container_name: ms-evaluacion
    ports:
      - "8083:8083"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/seguros_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - JPA_DDL_AUTO=update
    depends_on:
      - db

volumes:
  postgres_data:
  uploads_data:
